// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package file

import (
	"github.com/chenmingyong0423/go-mongox/v2"
	"server/internal/file/internal/api"
	"server/internal/file/internal/repo"
	"server/internal/file/internal/repo/dao"
	"server/internal/file/internal/service"
)

// Injectors from wire.go:

func InitFileModule(database *mongox.Database) *Module {
	fileDao := dao.NewFileDao(database)
	fileRepo := repo.NewFileRepo(fileDao)
	fileService := service.NewFileService(fileRepo)
	fileHandler := api.NewFileHandler(fileService)
	module := &Module{
		Hdl: fileHandler,
		Svc: fileService,
	}
	return module
}
