// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package label

import (
	"github.com/chenmingyong0423/go-mongox/v2"
	"github.com/codepzj/stellux/server/internal/label/internal/repository"
	"github.com/codepzj/stellux/server/internal/label/internal/repository/dao"
	"github.com/codepzj/stellux/server/internal/label/internal/service"
	"github.com/codepzj/stellux/server/internal/label/internal/web"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitLabelModule(mongoDB *mongox.Database) *Module {
	labelDao := dao.NewLabelDao(mongoDB)
	labelRepository := repository.NewLabelRepository(labelDao)
	labelService := service.NewLabelService(labelRepository)
	labelHandler := web.NewLabelHandler(labelService)
	module := &Module{
		Svc: labelService,
		Hdl: labelHandler,
	}
	return module
}

// wire.go:

var LabelProviders = wire.NewSet(web.NewLabelHandler, service.NewLabelService, repository.NewLabelRepository, dao.NewLabelDao, wire.Bind(new(service.ILabelService), new(*service.LabelService)), wire.Bind(new(repository.ILabelRepository), new(*repository.LabelRepository)), wire.Bind(new(dao.ILabelDao), new(*dao.LabelDao)))
