// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/chenmingyong0423/go-mongox/v2"
	"github.com/codepzj/stellux/server/internal/user/internal/repository"
	"github.com/codepzj/stellux/server/internal/user/internal/repository/dao"
	"github.com/codepzj/stellux/server/internal/user/internal/service"
	"github.com/codepzj/stellux/server/internal/user/internal/web"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitUserModule(mongoDB *mongox.Database) *Module {
	userDao := dao.NewUserDao(mongoDB)
	userRepository := repository.NewUserRepository(userDao)
	userService := service.NewUserService(userRepository)
	userHandler := web.NewUserHandler(userService)
	module := &Module{
		Svc: userService,
		Hdl: userHandler,
	}
	return module
}

// wire.go:

var UserProviders = wire.NewSet(web.NewUserHandler, service.NewUserService, repository.NewUserRepository, dao.NewUserDao, wire.Bind(new(service.IUserService), new(*service.UserService)), wire.Bind(new(repository.IUserRepository), new(*repository.UserRepository)), wire.Bind(new(dao.IUserDao), new(*dao.UserDao)))
