// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user_detail

import (
	"github.com/google/wire"
	"github.com/codepzj/Stellux/server/internal/user_detail/internal/repo"
	"github.com/codepzj/Stellux/server/internal/user_detail/internal/repo/dao"
	"github.com/codepzj/Stellux/server/internal/user_detail/internal/service"
	"github.com/codepzj/Stellux/server/internal/user_detail/internal/web"
)

// Injectors from wire.go:

func InitUserDetailModule() *Module {
	userDetailDao := dao.NewUserDetailDao()
	userDetailRepo := repo.NewUserDetailRepo(userDetailDao)
	userDetailService := service.NewUserDetailService(userDetailRepo)
	userDetailHandler := web.NewUserDetailHandler(userDetailService)
	module := &Module{
		Hdl:  userDetailHandler,
		Svc:  userDetailService,
		Repo: userDetailRepo,
	}
	return module
}

// wire.go:

var userDetailProvider = wire.NewSet(web.NewUserDetailHandler, service.NewUserDetailService, repo.NewUserDetailRepo, dao.NewUserDetailDao, wire.Bind(new(service.IUserDetailService), new(*service.UserDetailService)), wire.Bind(new(repo.IUserDetailRepo), new(*repo.UserDetailRepo)), wire.Bind(new(dao.IUserDetailDao), new(*dao.UserDetailDao)))
