// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package picture

import (
	"server/internal/picture/internal/api"
)

// Injectors from wire.go:

func InitPictureModule() *Module {
	pictureHandler := api.NewPictureHandler()
	module := &Module{
		Hdl: pictureHandler,
	}
	return module
}
