// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/codepzj/stellux/server/internal/ioc"
	"github.com/codepzj/stellux/server/internal/post"
	"github.com/codepzj/stellux/server/internal/user"
)

// Injectors from wire.go:

func InitApp() *HttpServer {
	database := ioc.NewMongoDB()
	module := user.InitUserModule(database)
	userHandler := module.Hdl
	postModule := post.InitPostModule(database)
	postHandler := postModule.Hdl
	v := ioc.InitMiddleWare()
	engine := ioc.NewGin(userHandler, postHandler, v)
	httpServer := NewHttpServer(engine)
	return httpServer
}
