<template>
  <div>
    <a-drawer
      :title="props.mode === 'edit' ? '编辑文章' : '发布文章'"
      :open="props.open"
      :width="width < 768 ? '100%' : '768px'"
      :footer-style="{ textAlign: 'right' }"
      @close="emit('update:open', false)"
    >
      <a-form
        ref="postFormRef"
        :model="postForm"
        :rules="rules"
        layout="vertical"
      >
        <a-row :gutter="16">
          <a-col :span="12">
            <a-form-item label="标题" name="title">
              <a-input
                v-model:value="postForm.title"
                placeholder="请输入标题"
                :maxlength="50"
              />
            </a-form-item>
          </a-col>
          <a-col :span="12">
            <a-form-item label="作者" name="author">
              <a-input
                v-model:value="postForm.author"
                placeholder="作者昵称"
              />
            </a-form-item>
          </a-col>
        </a-row>

        <a-row :gutter="16">
          <a-col :span="12">
            <a-form-item label="分类" name="category_id">
              <a-select
                v-model:value="postForm.category_id"
                placeholder="请选择分类"
              >
                <a-select-option
                  v-for="c in categories"
                  :key="c.id"
                  :value="c.id"
                >
                  {{ c.name }}
                </a-select-option>
              </a-select>
            </a-form-item>
          </a-col>
          <a-col :span="12">
            <a-form-item label="标签" name="tags_id">
              <a-select
                mode="multiple"
                v-model:value="postForm.tags_id"
                placeholder="请选择标签"
              >
                <a-select-option
                  v-for="t in tags"
                  :key="t.id"
                  :value="t.id"
                >
                  {{ t.name }}
                </a-select-option>
              </a-select>
            </a-form-item>
          </a-col>
        </a-row>

        <a-row :gutter="16">
          <a-col :span="12">
            <a-form-item label="封面" name="thumbnail">
              <div
                v-if="postForm.thumbnail"
                class="w-[200px] h-[112px] flex justify-center relative group"
              >
                <a-image
                  :src="postForm.thumbnail"
                  class="rounded-md cursor-pointer object-cover"
                  :preview="false"
                  @click="openThumbnailModal"
                />
                <div
                  class="absolute top-1 right-1 z-10 opacity-0 group-hover:opacity-100 transition-opacity"
                >
                  <a-button
                    type="primary"
                    shape="circle"
                    danger
                    size="small"
                    @click.stop="postForm.thumbnail = ''"
                  >
                    <CloseOutlined />
                  </a-button>
                </div>
              </div>
              <div
                v-else
                class="w-[200px] h-[112px] flex items-center justify-center border-2 border-dashed border-gray-300 rounded-md cursor-pointer text-gray-400"
                @click="openThumbnailModal"
              >
                <span class="text-sm">点击上传封面</span>
              </div>
            </a-form-item>
          </a-col>
        </a-row>

        <a-form-item label="描述" name="description">
          <a-textarea
            v-model:value="postForm.description"
            placeholder="请输入描述"
            :rows="2"
          />
          <a-button type="link" @click="autoGenerateDescription">
            自动截取
          </a-button>
        </a-form-item>

        <a-form-item label="内容" name="content">
          <a-textarea
            v-model:value="postForm.content"
            placeholder="请输入内容"
            :rows="6"
          />
        </a-form-item>

        <a-form-item label="发布时间" name="created_at">
          <a-date-picker show-time v-model:value="createdAt" />
        </a-form-item>

        <div class="flex items-center gap-2 my-4">
          <span>发布</span>
          <a-switch v-model:checked="postForm.is_publish" />
          <a-divider type="vertical" />
          <span>置顶</span>
          <a-switch v-model:checked="postForm.is_top" />
        </div>
      </a-form>

      <template #extra>
        <a-space>
          <a-button type="primary" @click="submitForm">
            发布
          </a-button>
          <a-button @click="emit('update:open', false)">取消</a-button>
        </a-space>
      </template>
    </a-drawer>

    <!-- 封面选择弹窗 -->
    <a-modal
      width="100%"
      wrap-class-name="full-modal"
      :open="thumbnailModalOpen"
      @update:open="thumbnailModalOpen = $event"
      title="选择封面"
      @ok="thumbnailModalOpen = false"
    >
      <PhotoWall
        mode="picture-card"
        type="select"
        :list="page.list"
        @selected-photos="handleSelectPicture"
      />
      <div class="flex justify-end my-4">
        <a-pagination
          v-model:current="page.page_no"
          :total="page.total_count"
          show-less-items
          @change="fetchThumbnails"
        />
      </div>
    </a-modal>
  </div>
</template>

<script lang="ts" setup>
import { ref, computed, reactive, onMounted } from "vue";
import { useWindowSize } from "@vueuse/core";
import { useRouter } from "vue-router";
import { message, type FormInstance } from "ant-design-vue";
import dayjs from "dayjs";

import { CloseOutlined } from "@ant-design/icons-vue";
import PhotoWall from "@/components/PhotoWall/index.vue";
import { queryAllByTypeAPI } from "@/api/label";
import { queryFileList } from "@/api/file";
import { createPostAPI, updatePostAPI } from "@/api/post";

import type { PostReq } from "@/types/post";
import type { LabelVO } from "@/types/label";
import type { FileVO } from "@/types/file";
import type { PageData } from "@/types/dto";

// Props & Emits
const props = defineProps<{
  mode: "create" | "edit";
  open: boolean;
  postForm: PostReq;
}>();

const emit = defineEmits<{
  (e: "update:open", value: boolean): void;
  (e: "update:postForm", value: PostReq): void;
}>();

// Router
const router = useRouter();

// 响应式表单对象
const postFormRef = ref<FormInstance>();
const postForm = computed({
  get: () => props.postForm,
  set: (val) => emit("update:postForm", val),
});

// 时间字段处理
const createdAt = computed({
  get: () => dayjs(postForm.value.created_at),
  set: (val) => (postForm.value.created_at = val.toISOString()),
});

// 校验规则
const rules = {
  title: [{ required: true, message: "请输入标题" }],
  content: [{ required: true, message: "请输入内容" }],
  description: [{ required: true, message: "请输入描述" }],
  thumbnail: [{ required: true, message: "请上传封面" }],
};

// 分类 / 标签
const categories = ref<LabelVO[]>([]);
const tags = ref<LabelVO[]>([]);

// 获取数据
const fetchCategories = async () => {
  const res = await queryAllByTypeAPI("category");
  categories.value = res.data;
};
const fetchTags = async () => {
  const res = await queryAllByTypeAPI("tag");
  tags.value = res.data;
};

// 自动生成描述
const autoGenerateDescription = () => {
  postForm.value.description = postForm.value.content
    .replace(/[\n\t]/g, " ")
    .replace(/<[^>]*>/g, "")
    .replace(/&(nbsp|amp|quot|apos);/g, "")
    .slice(0, 150)
    .trim();
};

// 提交处理
const submitForm = () => {
  postFormRef.value?.validate().then(async () => {
    if (props.mode === "create") {
      await createPostAPI(postForm.value);
      message.success("发布成功");
    } else {
      await updatePostAPI(postForm.value);
      message.success("编辑成功");
    }
    emit("update:open", false);
    router.push({ name: "PostList" });
  });
};

// 封面选择
const thumbnailModalOpen = ref(false);
const page = reactive<PageData<FileVO>>({
  page_no: 1,
  page_size: 10,
  total_count: 0,
  total_page: 0,
  list: [],
});

const openThumbnailModal = () => {
  fetchThumbnails();
  thumbnailModalOpen.value = true;
};

const fetchThumbnails = async () => {
  const res = await queryFileList({
    page_no: page.page_no,
    page_size: page.page_size,
  });
  page.list = res.data.list;
  page.total_count = res.data.total_count;
};

const handleSelectPicture = (pictures: string[]) => {
  postForm.value.thumbnail = pictures[0];
};

// 屏幕尺寸
const { width } = useWindowSize();

// 初始化
onMounted(() => {
  fetchCategories();
  fetchTags();
});
</script>

<style lang="scss">
.full-modal {
  .ant-modal {
    max-width: 100%;
    top: 0;
    margin: 0;
    padding-bottom: 0;
  }
  .ant-modal-content {
    display: flex;
    flex-direction: column;
    height: 100vh;
  }
  .ant-modal-body {
    flex: 1;
    overflow-y: auto;
  }
}

::-webkit-scrollbar {
  width: 8px;
}
</style>
