// 根据守卫路由的name获取对应的路由中文名
export const routeNames = {
  Dashboard: "仪表盘",
  UserList: "用户列表",
  UserRole: "用户角色",
  PublishArticle: "发布文章",
  ArticleList: "文章列表",
  Draft: "草稿箱",
  MaterialLibrary: "素材库",
  RecycleBin: "回收站",
  Interaction: "互动管理",
  Comment: "评论管理",
  Like: "点赞管理",
  Message: "私信管理",
  DataAnalysis: "数据分析",
  ArticleStatistics: "文章统计",
  UserStatistics: "用户统计",
  InteractionStatistics: "互动统计",
  SystemNotifications: "系统通知",
  UserNotifications: "用户通知",
  SystemSettings: "系统设置",
  SystemConfig: "系统设置",
};
