// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"server/internal/ioc"
	"server/internal/posts"
	"server/internal/user"
)

// Injectors from wire.go:

func InitApp() *HttpServer {
	envConfig := ioc.InitEnv()
	database := ioc.NewMongoDB(envConfig)
	module := user.InitUserModule(database)
	userHandler := module.Hdl
	postsModule := posts.InitPostsModule(database)
	postsHandler := postsModule.Hdl
	v := ioc.InitMiddleWare()
	engine := ioc.NewGin(userHandler, postsHandler, v)
	httpServer := NewHttpServer(engine, envConfig)
	return httpServer
}
