// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package posts

import (
	"github.com/google/wire"
	"github.com/codepzj/Stellux/server/internal/posts/internal/repo"
	"github.com/codepzj/Stellux/server/internal/posts/internal/repo/dao"
	"github.com/codepzj/Stellux/server/internal/posts/internal/service"
	"github.com/codepzj/Stellux/server/internal/posts/internal/web"
)

// Injectors from wire.go:

func InitPostsModule() *Module {
	postsDao := dao.NewPostsDao()
	postsRepo := repo.NewPostsRepo(postsDao)
	postsService := service.NewPostsService(postsRepo)
	postsHandler := web.NewPostHandler(postsService)
	module := &Module{
		Hdl:  postsHandler,
		Svc:  postsService,
		Repo: postsRepo,
	}
	return module
}

// wire.go:

var postsProvider = wire.NewSet(web.NewPostHandler, service.NewPostsService, repo.NewPostsRepo, dao.NewPostsDao, wire.Bind(new(service.IPostsService), new(*service.PostsService)), wire.Bind(new(repo.IPostsRepo), new(*repo.PostsRepo)), wire.Bind(new(dao.IPostsDao), new(*dao.PostsDao)))
