// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package document

import (
	"github.com/chenmingyong0423/go-mongox/v2"
	"github.com/codepzj/stellux/server/internal/document/internal/repository"
	"github.com/codepzj/stellux/server/internal/document/internal/repository/dao"
	"github.com/codepzj/stellux/server/internal/document/internal/service"
	"github.com/codepzj/stellux/server/internal/document/internal/web"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitDocumentModule(mongoDB *mongox.Database) *Module {
	documentDao := dao.NewDocumentDao(mongoDB)
	documentRepository := repository.NewDocumentRepository(documentDao)
	documentService := service.NewDocumentService(documentRepository)
	documentHandler := web.NewDocumentHandler(documentService)
	module := &Module{
		Svc: documentService,
		Hdl: documentHandler,
	}
	return module
}

// wire.go:

var DocumentProviders = wire.NewSet(web.NewDocumentHandler, service.NewDocumentService, repository.NewDocumentRepository, dao.NewDocumentDao, wire.Bind(new(service.IDocumentService), new(*service.DocumentService)), wire.Bind(new(repository.IDocumentRepository), new(*repository.DocumentRepository)), wire.Bind(new(dao.IDocumentDao), new(*dao.DocumentDao)))
